import { Link } from "react-router-dom";
import Icon from "../components/Icon";
import Reveal from "../components/Reveal";
const values=[["01","Whole foods","Thoughtful meals can prioritize variety, freshness and appropriate nutritional needs."],["02","Cultural variety","Food can carry culture, memories and connection. A home should have room for different traditions."],["03","Personal preferences","Meal planning should consider individual preferences, dietary requirements and approved care plans."],["04","Whole-person routines","Wellness can include rest, movement, social connection, meaningful activity and time to recharge."]];
const examples=["Mediterranean-inspired chicken with fresh vegetables","East African-inspired lentils and leafy greens","Grilled fish with seasonal vegetables","Turkey and vegetable dishes","Fresh fruit, yogurt and nourishing snacks","Herbal teas and hydrating beverages"];
export default function Wellness(){return <main id="main-content">
<section className="page-hero"><div className="container page-hero-content"><Reveal><span className="eyebrow">Food & wellness</span><h1>Nourishing from the inside out.</h1><p>Wellness lives in the ordinary: a favorite meal, a familiar routine, a shared conversation, a walk outside or an activity that gives the day meaning.</p></Reveal></div></section>
<section className="section"><div className="container content-grid"><Reveal variant="left"><div className="content-copy"><span className="eyebrow">Our approach</span><h2>Food is part of the care experience.</h2><p>Meals are more than something placed on a table. They can create routine, comfort, connection and enjoyment.</p><p>BVK's wellness approach leaves room for individual needs and preferences while recognizing that dietary decisions may require appropriate professional guidance.</p></div></Reveal><Reveal variant="right"><div className="wellness-card"><span>BVK WELLNESS</span><h3>Fresh.<br/>Thoughtful.<br/>Personal.</h3><p>Every resident's dietary needs and care plan should guide what is appropriate.</p></div></Reveal></div></section>
<section className="section values-section"><div className="container"><Reveal><div className="section-heading"><span className="eyebrow">What we value</span><h2>Wellness with the individual in mind.</h2></div></Reveal><div className="feature-grid">{values.map(([n,t,p],i)=><Reveal key={n} delay={i*80}><article className="feature-card"><span className="feature-number">{n}</span><h3>{t}</h3><p>{p}</p></article></Reveal>)}</div></div></section>
<section className="section journey"><div className="container wellness-layout"><Reveal variant="left"><div className="journey-copy"><span className="eyebrow">A taste of BVK</span><h2>Variety belongs at the table.</h2><p>Examples of food ideas can inspire menus without turning them into rigid promises. Individual preferences and dietary guidance come first.</p></div></Reveal><div className="service-list">{examples.map((item,i)=><Reveal key={item} delay={i*55}><div className="service-item"><div className="service-icon"><Icon name="check" size={20}/></div><div><p>{item}</p></div></div></Reveal>)}</div></div></section>
<section className="page-cta"><div className="container page-cta-content"><Reveal><span className="eyebrow">Learn more</span><h2>Have questions about our wellness approach?</h2><p>Talk with BVK about our home environment, food philosophy and resident-centered approach.</p><Link to="/contact" className="primary-button">Contact BVK <Icon name="arrow" size={17}/></Link></Reveal></div></section>
</main>}
